// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Como.SDK.Models
{
    using Como.SDK;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Agenda
    {
        /// <summary>
        /// Initializes a new instance of the Agenda class.
        /// </summary>
        public Agenda()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Agenda class.
        /// </summary>
        public Agenda(string eventID = default(string), System.Guid? id = default(System.Guid?), IList<Session> sessions = default(IList<Session>))
        {
            EventID = eventID;
            Id = id;
            Sessions = sessions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eventID")]
        public string EventID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sessions")]
        public IList<Session> Sessions { get; set; }

    }
}
